# name: Build project

# on: [push, pull_request]

# jobs:
#   buildForAllSupportedPlatforms:
#     name: Build for ${{ matrix.targetPlatform }}
#     runs-on: ubuntu-latest
#     strategy:
#       fail-fast: false
#       matrix:
#         targetPlatform:
#           - StandaloneOSX # Build a macOS standalone (Intel 64-bit).
#           - StandaloneWindows # Build a Windows standalone.          
#           - WebGL # WebGL.
#           - StandaloneLinux64 # Build a Linux 64-bit standalone.
#           - iOS # Build an iOS player.
#           - Android # Build an Android .apk standalone app.           
#     steps:
#       # Checkout the repository with full history and LFS support
#       - uses: actions/checkout@v4
#         with:
#           fetch-depth: 0
#           lfs: true
#       # Cache Unity Library folder to speed up builds
#       - uses: actions/cache@v3
#         with:
#           path: Library
#           key: Library-${{ matrix.targetPlatform }}
#           restore-keys: Library-
#       # Free up disk space for Android builds (they require more space)
#       - if: matrix.targetPlatform == 'Android'
#         uses: jlumbroso/free-disk-space@v1.3.1
#       # Build the Unity project for the target platform
#       - uses: game-ci/unity-builder@v4
#         env:
#           UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
#           UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
#           UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
#         with:
#           targetPlatform: ${{ matrix.targetPlatform }}
#       # Upload the build artifacts
#       - uses: actions/upload-artifact@v4
#         with:
#           name: Build-${{ matrix.targetPlatform }}
#           path: build/${{ matrix.targetPlatform }}
